checks:
    php: true
filter:
    excluded_paths: [vendor/*, tests/*]
coding_style:
    php: {  }
tools:
    external_code_coverage: true
    php_code_coverage: true

before_commands:
    - sudo apt-get update
    - sudo apt-get install -y openssl libssl-dev pkg-config
    - export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
